### ISSUE TITLE
split keyboard dvorak base score is higher than qwerty base?

### ISSUE THREAD

**Issue by waynehoover** [jackhumbert/typing_model#1]
Why is it that split keyboards with a dvorak layout have a higher total effort?

If you take a look at the two qmk layouts attached (remove .txt extension as I had to change it to that to make github happy) I would expect that the dvorak version to have a lower score than the qwerty version for the same split keyboard. 

When I tested the dvorak version to the qwerty version on the planck the dvorak version had a lower score as expected. I have tested this on other split keyboards like the iris and still the same result of the dvorak version having a higher score appears.

[lilydvorak.json.txt](https://github.com/jackhumbert/typing_model/files/3883921/lilydvorak.json.txt)
[lilydefault.json.txt](https://github.com/jackhumbert/typing_model/files/3883922/lilydefault.json.txt)

**Comment by jackhumbert** [comment]
Dvorak wasn't supported in the automatic homerow finding, so it was getting moved up a row :) should be fixed as of d2fc3b5!

![image](https://user-images.githubusercontent.com/141431/69600905-56b4c580-0fe0-11ea-9790-9ba8f031a0ac.png)
