### ISSUE TITLE
Keymaps not loading

### ISSUE THREAD

**Issue by h-sinki** [jackhumbert/typing_model#5]
When I select a keymap from the drop-down and click 'Load', nothing loads. 
There are 3 network requests:
Get to https://config.qmk.fm/keymaps/c/ckeys_washington_default.json - status 200
Get to https://api.qmk.fm/v1/keyboards/ckeys/washington - status 300
Get to https://keyboards.qmk.fm/v1/keyboards/%3Ckeyboard%3E/info.json - status 404

**Comment by jackhumbert** [comment]
Thanks for reporting! Should be fixed now.
